services:
  mongo:
    image: mongo:6.0.13-jammy
    # restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    # restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGO_URI}

  them-tube-api:
    build:
      dockerfile: ./Dockerfile
    # restart: always
    depends_on:
      - mongo
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app:rw
    environment:
      MONGO_URI: ${MONGO_URI}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_DAYS: ${ACCESS_TOKEN_EXPIRE_DAYS}
      DATABSE_NAME: ${DATABSE_NAME}
      DATABSE_SERVICE: ${DATABSE_SERVICE}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
      

volumes:
  dbdata:
    name: them-tube-mongo-db
 